version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  BeforeInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_nginx.sh
      timeout: 300
      runas: root
